### ISSUE TITLE
Unable to compile Holographic Player App

### ISSUE THREAD

**Issue by DeadlyMagikarps** [microsoft/MixedReality-HolographicRemoting-Samples#103]
I've been unable to compile the Holographic Remoting player app following the readme that is provided. (The pre-packaged one works, but there are use cases that we would like so the custom route makes the most sense.) However, I can't compile it as is.

I've installed all the required components for an ARM64 build for the Hololens 2. I'm compiling as is without modification right now. Nuget Packages was restored.

The error isn't helpful either: 

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB6006	"fxc.exe" exited with code 1.	SamplePlayer	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	1847		

```

I'm unsure if it's dependent on something else in the repository as I moved the "player" folder somewhere else and opened the solution SamplePlayer from there. Seems like it is related to the shaders and I'm unsure what settings is needed in visual studio.

Using the latest Visual Studio 2022 version: 17.10.3
OS: Windows 10 Enterprise Version 10.0.19045 Build 19045

Any guidance would be appreciated.

**Comment by chairobl** [comment]
Hi @DeadlyMagikarps ,
fxc.exe is indeed Visual Studio's [in-built HLSL shader compiler](https://learn.microsoft.com/en-us/windows/win32/direct3dtools/fxc). Based on you having copied the "player" folder I'm guessing that you forgot to also copy the "common" folder which contains shaders and other files used by both the player and remote projects. When fxc.exe is ran as part of the build it fails to find the shader files and exits with error code 1.

**Comment by DeadlyMagikarps** [comment]
@chairobl 

For more clarity,

The common folder is in the same spot as in the examples for this repo.

I checked the HLSL Compiler Settings under Configuration Properties and tried several options. 

Such as looking at the Additional Include Directories. Which shows the common/Content and sample/shaders

Changed Shader Tyler to Pixel Shader, Shader Model, I've tried a few including 5.1.

But the versions doesn't seem to be effecting the compilation and still get the fxc.exe error. 

I must be something stupid simple and I'm just not seeing it.

**Comment by DeadlyMagikarps** [comment]
@chairobl I'll be damned. 

That's what I was missing. The top level shaders folder.

Thanks for mentioning that! It compiles and launched on the headset.

Marking it closed. 

For future reference to others for just the player app compilation:

common 
player
- common
- sample
