### ISSUE TITLE
Question: Clarification on Version 2.9.4 patch notes

### ISSUE THREAD

**Issue by dnikolaidis2** [microsoft/MixedReality-HolographicRemoting-Samples#106]
Hello,

Thank you for the continued support of holographic remoting! I have one question about the most recent patch notes. When you state that "Fixed erraneous pinch gap values leading to unwanted interactions" could you elaborate on which specific output that was corrected?

Thank you in advance!

**Comment by chairobl** [comment]
Hi @dnikolaidis2,
of course! We saw multiple users reporting [pinchgap issues ](https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/issues/167)in 2.8.0+, which has now been remedied in 2.9.4. This means that pinch interactions now again work as they should.
