### ISSUE TITLE
Graphics Debugging

### ISSUE THREAD

**Issue by Halven08** [microsoft/MixedReality-HolographicRemoting-Samples#12]
When trying to connect to the HoloLens 2 while graphics debugging is on there is information that: 
`Disconnect: Transport connection was closed due to the requested video format not being available`

It works like that for `PreferredVideoCodec::Any` and `PreferredVideoCodec::H264` and by `PreferredVideoCodec::H265` and error `SampleRemote.exe: WinRT originate error - 0x80004005 : 'Cannot find an encoder for the requested video codec.'.` is thrown.

Tried it with the 2.2.2. sample version.
It was possible to use graphics debugging with the HoloLens 1 and it was a useful feature.

**Comment by FlorianBagarMicrosoft** [comment]
Which graphics debugger are you using? Pix, Visual Studio graphics debugger, or RenderDoc?

**Comment by Halven08** [comment]
Visual Studio graphics debugger

**Comment by FlorianBagarMicrosoft** [comment]
@Halven08, we are able to reproduce the issue and will get back to you as soon as we know more.

**Comment by FlorianBagarMicrosoft** [comment]
@Halven08, the Holographic Remoting stack internally uses DirectX 12 for a couple of things in the video encoding/decoding context. Unfortunately the Visual Studio graphics debugger does not support DirectX 12 as stated [here](https://docs.microsoft.com/visualstudio/debugger/graphics/visual-studio-graphics-diagnostics-directx-12). We also recommend PIX on Windows.
