### ISSUE TITLE
Incompatible with Mixed Reality Capture from PV camera

### ISSUE THREAD

**Issue by qian256** [microsoft/MixedReality-HolographicRemoting-Samples#15]
I wanted to run mixed reality capture with opt-in PV camera when the HL2 is running remote player. I inserted the following code into the initialization stage of the app (after the remote player context is initialized):
```
auto display = winrt::Windows::Graphics::Holographic::HolographicDisplay::GetDefault();
auto mrcViewConfiguration = display.TryGetViewConfiguration(winrt::Windows::Graphics::Holographic::HolographicViewConfigurationKind::PhotoVideoCamera);
if (mrcViewConfiguration != nullptr) {
        mrcViewConfiguration.IsEnabled(true);
}
```
However, the `mrcViewConfiguration` keeps being nullptr.
If I inserted this block of code before remote player context is initialized, the app will crash when MRC starts.
What is the correct way to opt-in PV camera MRC when HL2 is running remote player? Is it done on the PC side (the remote app)?

**Comment by qian256** [comment]
After digging into the remote app (PC), I found that opt-in PV from PC app does not make sense because the desktop does not have a PV camera like a headset. The question is then, how can we manually add a HolographicCamera to the remote app to render an additional color+depth frame corresponding to the PV camera on the headset (view transformation, target size etc), and send to the HL2 for MRC?

**Comment by FlorianBagarMicrosoft** [comment]
Unfortunately the opt-in PV camera is not supported with Holographic Remoting. It would require additional video streams which is currently quite problematic with consumer grade GPUs because these usually only support two simultaneous video streams. Holographic Remoting is already using two streams for color and depth at the moment.

**Comment by qian256** [comment]
I see. Thank you for clarification.
