### ISSUE TITLE
Trying to understand "Remote Context"

### ISSUE THREAD

**Issue by qian256** [microsoft/MixedReality-HolographicRemoting-Samples#16]
From the [Holographic Remoting](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/holographic-remoting-create-host) document, it writes that:
> Holographic Remoting works by replacing the Windows Mixed Reality runtime which is part of Windows with a remoting specific runtime. This is done during the creation of the remote context. For that reason any call on any Windows Mixed Reality API before creating the remote context can result in unexpected behavior.

Does it mean that the default locator of the remote side is exactly same as the default locator on HL2, so that every spatial transform on the remote side matches the transform on HL2?

**Comment by FlorianBagarMicrosoft** [comment]
No it does not. The default locator on the remote side is different to the one on the HL2. You should not assume any relation between coordinate systems on the remote side and the HL2 side.

**Comment by qian256** [comment]
@FlorianBagarMicrosoft Thank you for clarification. Do you have any idea about how could we possibly obtain the relative transformation between the two at runtime? Either in Unity or in UWP

**Comment by FlorianBagarMicrosoft** [comment]
What are you trying to achieve, say what's your use-case?

**Comment by qian256** [comment]
The use case is that, I obtain the pose of sensors (e.g. PV camera) in HL2, which is defined in the HL2 world space. And I want to correctly position the sensor in a Unity scene as a secondary scene camera. With an unknown offset between the HL2 world and Unity world, the transformation matrix of sensor from HL2 world does not have any real meaning in Unity.

**Comment by qian256** [comment]
The "offset" should be known because, I assume Unity takes the HL2 main camera (HolographicCamera) pose per frame and use this offset to setup virtual camera in Unity world

**Comment by FlorianBagarMicrosoft** [comment]
If I understood you correctly this is not about Holographic Remoting but about how to access the SpatialCoordinateSystem (https://docs.microsoft.com/uwp/api/windows.perception.spatial.spatialcoordinatesystem) Unity is using for its world space so that you can compute the offset between your own SpatialCoordinateSystem and Unity's one, right?

**Comment by qian256** [comment]
Not exactly. It is under the remoting setting. So the HL2 is running remoting player, and a Unity application is running on PC as remoting server. I obtain the pose of sensors in HL2, and send it back to PC, then I cannot put the sensors in correct pose in Unity because of the offset. I would like to know how could this offset be obtained, since it is being used for the rendering camera as well. I assume the HL2 also sends the "HolographicCamera" pose to Unity and Unity puts it in its own spatial coordinate system with some offset

**Comment by FlorianBagarMicrosoft** [comment]
Holographic Remoting internally uses the concept of a virtual coordinate system to send data from the HL2 to the PC. Spatial coordinate systems used by remote apps (like your Unity app) are purely create on the remote PC side but are anchored in this virtual coordinate system. This allows Holographic Remoting to express camera pose data send from the HL2 to the remote PC in the remote app's spatial coordinate system.
I guess with "pose of sensors" you mean additional data you send on your own form the HL2 to the remote PC? Say data not send by Holographic Remoting.

**Comment by qian256** [comment]
Yes. I am trying to send additional data (poses of sensors expressed in HL2 coordinates) to remote PC

**Comment by qian256** [comment]
The concept of virtual coordinate system is interesting. What I would like to know is exactly where Unity puts its world anchor in HL2's world, and is there any way to obtain this information?

**Comment by FlorianBagarMicrosoft** [comment]
Are you trying to use the MediaFrameReference (https://docs.microsoft.com/windows/mixed-reality/develop/platform-capabilities-and-apis/locatable-camera#using-mediaframereference)?

**Comment by qian256** [comment]
Yes I use this to obtain the pose of PV camera in HL2's world, but I would like to represent it in the remote PC's Unity's coordinate system.

**Comment by FlorianBagarMicrosoft** [comment]
I see, unfortunately this particular use-case is currently not possible with Holographic Remoting.
A work-around could be if you calculate the delta between the PV camera pose and the head pose (https://docs.microsoft.com/uwp/api/windows.ui.input.spatial.spatialpointerpose) on the HL2. This delta gets send over to the PC running the remote app. Then you query the head pose on the remote side and apply the delta. It would not be perfectly in sync but depending on the purpose of this it might be good enough.

**Comment by ai-710** [comment]
Hey! 
I am trying to do something similar, but I am not using MediaFrameReference. From what I understand, the HL2 stream the video and the audio to the remote server (PC) and the scene is then processed in there. What I was trying to do is to detect the QR code on the player part, and send the information of the code (like the position as a transformation matrix) to the server. Is it possible to do this in some way? i.e. by using Customized Data Channels?

**Comment by FlorianBagarMicrosoft** [comment]
@ai-710, the HL2 does not stream video or audio to the remote server (PC). It's the other way around, say the HL2 streams pose data (information about the position of the device in space) to the remote PC, there your remote app renders an image for that pose data which is then video encoded by Holographic Remoting and streamed back to the HL2.

Concerning QR codes, this is working out of the box with Holographic Remoting, have a look at:
- https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/blob/master/remote/desktop/Content/QRCodeTracker.h
- https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/blob/master/remote/desktop/Content/QRCodeRenderer.h

**Comment by ai-710** [comment]
@FlorianBagarMicrosoft according to your reply, does it mean that the HL2 are the ones that detect the pose of the QRCode and send that info to the server (PC). Because if it is not, I would understand that at least the server should receive an image to render the holograms. 

I can see how the QRCode tracking happens but I was trying to put this code in the SamplePlayer.

**Comment by FlorianBagarMicrosoft** [comment]
Exactly, the HL2 (player app) detects the pose of the QRCode and sends that info to the remote PC.
Why do you want to put the QRCode tracking into the SamplePlayer? Where do you need the QRCode info/data, in your player or in your remote app?

**Comment by ai-710** [comment]
Ok, thanks! 

I thought the HL2 did not detect the QRCode and that was done directly on the server (PC). I need to manipulate the data that arrives from the HL2 like the pose of the QRCode on the remote server to be able to render different scenes in there. Basically what the sample itself does, but I cannot see where this data manipulation occurs, meaning that I cannot see how the ReceivedData is manipulated.

**Comment by FlorianBagarMicrosoft** [comment]
For every QRCode you can use the QRCode GUID to get a coordinate system via CreateCoordinateSystemForNode (https://docs.microsoft.com/uwp/api/windows.perception.spatial.preview.spatialgraphinteroppreview.createcoordinatesystemfornode#Windows_Perception_Spatial_Preview_SpatialGraphInteropPreview_CreateCoordinateSystemForNode_System_Guid_).
With that coordinate system you can render what every you like at the location/pose of the QRCode. What else do you need?

**Comment by ai-710** [comment]
That's ok! Thanks for the explanation!

**Comment by FlorianBagarMicrosoft** [comment]
@qian256, closing this one.

**Comment by luoxiali** [comment]
it's so upset that i encounter like the same question,when i using the 'connect' command in order to scan the QR code,but nothing changed on my hololens2,it's seem the holographic remoting player can't recognize the voice command,but the command 'enable diagnostics' can be recognized in my holographic remoting player v2.9.2.0,anyone can help me of that?

**Comment by simonrobl** [comment]
Hi @luoxiali,
I have replied to you in a new issue [here](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/issues/97) :)
