### ISSUE TITLE
No hologram on HoloLens 2

### ISSUE THREAD

**Issue by OsparkSolutions** [microsoft/MixedReality-HolographicRemoting-Samples#18]
I built and ran the remote UWP sample project. It runs and connects to the Holographic Remoting Player (v2.3.1.0). The preview on my machine shows the cube and my hand movements & rays.
![image](https://user-images.githubusercontent.com/53837163/100265438-40f11d80-2f1e-11eb-9ac0-14a750e0953b.png)

However nothing is visible through the HoloLens device. I ran into the same issue when trying to connect through unity. So I'm not sure if this is a bug with the current version of the MRTK or the device. Any help would much be appreciated (including being pointed to a better place to report this issue)

**Comment by FlorianBagarMicrosoft** [comment]
Could you try to switch the video codec to H264?

You can do this by changing the remote context creation from:
  CreateRemoteContext(m_remoteContext, 20000, true, PreferredVideoCodec::Any);
to
  CreateRemoteContext(m_remoteContext, 20000, true, PreferredVideoCodec::H264);

**Comment by OsparkSolutions** [comment]
That worked! Thanks for the response!
