### ISSUE TITLE
[winrt] SpatialAnchorManager unstable/not working when remoting

### ISSUE THREAD

**Issue by xiaoguid** [microsoft/MixedReality-HolographicRemoting-Samples#20]
I'm having issues with SpatialAnchorManager on remote sessions.

Using the latest Holographic Remoting player app, C++ nuget package 2.4.0 on winrt, HL2 latest OS version.
(also happens with 2.3.1, not sure about previous packages).

3 out of 4 times SpatialAnchorManager::RequestStoreAsync() never calls the Completed callback and is unavailable for the duration of the session.

SpatialSurfaceObserver::RequestAccessAsync and EyesPose::RequestAccessAsync always work for comparison.

I've tested several methods: calling RequestStoreAsync before connecting a session, on session connect, only when trying to save/load an anchor (after a while) and even polling in a dedicated worker thread. 

The results are the same, on most of the sessions the callback never completes until I disconnect the session (causing all blocked callbacks to immediately return with an error).

When it does work and I get a valid SpatialAnchorStore saving does not persist even when SpatialAnchorStore::TrySave() returns true, it only persists until disconnecting.
The next 'valid' session (reconnecting / running the app again) most of the time returns an empty SpatialAnchorStore or none at all.

I did manage to get it to work intermediately by first clearing the anchor store and then saving the anchor 10 times in a row.
Disconnect then throws lots of "RemotingHandlerCore_AnchorStoreRemoveAnchor_Failed" but sometimes the new saved anchor persists. (I make sure to remove the anchor if it already exists before calling TrySave.)

It feels like something is blocked or blocking the data received/sent to SpatialAnchorStore which is only half flushed on Disconnect. Sometime only the SpatialAnchorStore::GetAllSavedAnchors Clear()/Remove persists ignoring the following TrySave.

Other callbacks (such as querying spatial surfaces meshes) work fine all the time.

Here is how I am requesting the store:

storeRequest = winrt::Windows::Perception::Spatial::SpatialAnchorManager::RequestStoreAsync();
storeRequest.Completed([this](winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Perception::Spatial::SpatialAnchorStore> result, auto asyncStatus) 
{ 
  // most of the times never called or only called on Disconnect with an error
}

I am on a stable local wifi, remote tracking and creating local anchors (without save/load to store) all work fine.

Any ideas? 
Much appreciated.

**Comment by FlorianBagarMicrosoft** [comment]
Thanks for raising this! We will look into the issue and get back to you as soon as we know more.

**Comment by xiaoguid** [comment]
Hi @FlorianBagarMicrosoft is there any update on this?
I can further confirm this only happens on Hololens2.

On Hololens1 the request for SpatialAnchorStore always works as expected, as well as saving and loading anchors. 

Both implementations share the same anchor winrt code so this really seems to be something specific to Hololens2 with the new remoting packages.

Please let me know if you need any additional information or if there is any way to follow up on this in more detail.

**Comment by NPohl-MSFT** [comment]
Hi @xiaoguid,
thanks again for raising this. 

We were able to reproduce the issues you mentioned, and will fix them with the next update.

**Comment by xiaoguid** [comment]
@NPohl-MSFT that's great to hear, thanks.

By issues do you mean the update will also include a fix for #21 ?

**Comment by NPohl-MSFT** [comment]
@xiaoguid, thank you for bringing this to our attention.
We were able to reproduce the exceptions and fixed it with the next release.

In the meantime, the following setting might help:
By default, the Visual Studio debugger breaks when winrt::hresult_error exceptions are thrown. You can disable the debugger from doing this via the Exception Settings (Debug -> Windows -> Exception settings). In the Exception Settings window, untick C++ Exceptions -> winrt::hresult_error.
