### ISSUE TITLE
Holographic remoting speech recognition deteriorates over time

### ISSUE THREAD

**Issue by xiaoguid** [microsoft/MixedReality-HolographicRemoting-Samples#21]
This goes all the way to HL1 with remoting package 1.0, but happens quite often on HL2 specifically (multiple devices).

When remoting using the official holographic remoting app (2.3.1-2.4.0, matching package): the longer the app remains open on the device across/between sessions - remote speech recognition will become progressively worse until it doesn't work at all. 

This happens even with a simple dictionary like {"hello world", "move", "change", "help"} etc.

C++/winrt Speech recognition code is exactly like in the samples.

Consistently, on the first run everything is recognized (with high confidence). 
The longer the holographic remoting app is running and sessions connect/disconnect the worse recognition will get over time. (quiet environment).

There are two main reasons I think it has something to do with the official app:

1) Closing and reopening the holographic remoting app on the device magically fixes speech recognition every time.

2) Even when remote speech recognition doesn't work at all in the remote app, opening the start menu and speaking recognizes everything flawlessly. 
So if the system speech recognition still works great while the remote speech doesn't work at all, it clearly hints at a local issue.

We've been having this issue ever since HL1 but it seems to have gotten worse with HL2 and the new remoting versions.

I was wondering if this was a known issue and if you can please fix this?

Thanks!

**Comment by FlorianBagarMicrosoft** [comment]
Thanks for the feedback! We will look into this issue and get back to you as soon as we know more.

**Comment by xiaoguid** [comment]
Hi @FlorianBagarMicrosoft, I was wondering if there is any update on this?
The issue is pretty easy to reproduce if you work with remoting consecutively for a while (more than a few mins).
Please let me know if you need any additional information.

**Comment by FlorianBagarMicrosoft** [comment]
@xiaoguid, we can reproduce the issue and double checked Holographic Remoting's speech implementation which is using the SpeechRecognizer (https://docs.microsoft.com/uwp/api/windows.media.speechrecognition.speechrecognizer) from the Windows SDK. The issue is that the SpeechRecognizer does not reliably trigger speech results, thus we reached out to our Speech and Language Team on that matter. They asked us if you could report the issue via the feedback hub on your HoloLens. This will help them to get more data form the device the issue is happening on. Please use **Input and Language** + **Speech Input** when you choose a category for your feedback hub issue.

**Comment by xiaoguid** [comment]
Thanks @FlorianBagarMicrosoft. Reported the issue using the feedback hub, basically linking back here.

Have to say that reporting bugs from within Hololens (plus the entire on-device feedback hub concept) is one of the most inconvenient and silly things wrt Hololens development :)

Currently not having speech recognition working properly within Holographic Remoting is a pretty major issue and breaks lots of AR functionality.

I understand this is a cross-group bug within MS, is there anything further we can do except wait and ping about this later?

**Comment by maapp** [comment]
Hi @xiaoguid.

Just wanted to let you know that we updated the internal ticket for the speech team with the information we gathered on our side.
I hope this helps getting traction on this sooner than later. Sorry for the inconvenience, I really hope we get this solved quickly.

Bye,
Marc

**Comment by xiaoguid** [comment]
Thanks @maapp for the update, much appreciated.
Really hoping this gets fixed asap, it completely breaks our app.
Currently as a workaround we are working to replace speech recognition with a hand UI on HL2.

**Comment by maapp** [comment]
Hi @xiaoguid,

sorry it took a while but I have good news! With the remoting version we just released (2.6.1) we fixed the speech issue. You should just need to update the player on your HoloLens to get the fix.
