### ISSUE TITLE
OpenXR remoting extension

### ISSUE THREAD

**Issue by Holo-Krzysztof** [microsoft/MixedReality-HolographicRemoting-Samples#22]
I've just stumbled across [these OpenXR extensions](https://htmlpreview.github.io/?https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/blob/master/remote_openxr/specification.html) and I have a few questions:

- Are they always going to be MSFT-specific or are there plans for making them cross-vendor/cross-runtime?
- Will they become part of the default OpenXR runtime shipped on devices? As far as I understood they live in a separate runtime implementation now, shipped inside a nuget package.

**Comment by FlorianBagarMicrosoft** [comment]
@Holo-Krzysztof, the XR_MSFT_holographic_remoting extension is quite specific to Holographic Remoting and will most likely stay a MSFT-specific extension shipped with Holographic Remoting OpenXR runtime. The XR_MSFT_remoting_frame_mirroring extension could be supported by other runtimes as well, as it basically just gives the user access to the final composed (incl. quad layers, etc.) image, but at the moment it's not planned.

**Comment by Holo-Krzysztof** [comment]
Thanks for the clarification! :)
