### ISSUE TITLE
Unable to build SampleRemoteOpenXR: VcToolsVersion.14.26.props was not found

### ISSUE THREAD

**Issue by vulkan101** [microsoft/MixedReality-HolographicRemoting-Samples#23]
I get the following error when trying to build (with visual studio Professional) 

`The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\14.26\Microsoft.VCToolsVersion.14.26.props" was not found. Confirm that the expression in the Import declaration "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/14.26/Microsoft.VCToolsVersion.14.26.props" is correct, and that the file exists on disk.
`

To workaround, I have to change this in the project file to point at the best approximation I have, which is `Microsoft Visual Studio/2019/Professional/VC/Auxiliary/Build/Microsoft.VCToolsVersion.v142.default.props`

Can this be set up so that it doesn't require the user to find and fix this?

**Comment by Hanaaelg** [comment]
For now, you can remove the line `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\14.26\Microsoft.VCToolsVersion.14.26.props` from the file "SampleRemoteOpenXR.vcxproj" and it should build successfully. This will be fixed with the next update for the samples.
