### ISSUE TITLE
[winrt] thrown exceptions on Disconnect/Close

### ISSUE THREAD

**Issue by xiaoguid** [microsoft/MixedReality-HolographicRemoting-Samples#25]
Hi @NPohl-MSFT, bringing this up again as you've closed #20.

Unfortunately with 2.5.0 I'm still getting similar exceptions on disconnect and close.
It basically crashes the program when calling Disconnect.

If those exceptions are valid and the expected behavior is to disable the exceptions under the debugger (winrt::hresult_error), then it sounds pretty backwards to me. 

IMO if everything worked until that point, exceptions on Disconnect/Close should be somehow handled internally or not thrown at all.

I understand the debugger by default breaks on winrt::hresult_error, but after calling Disconnect you can't really do anything about those exceptions and just want the thing to cleanly disconnect without throwing 200 exceptions or having to disable them and miss others :)

Please let me know if you want more exception logs - essentially very similar to #20 .
Much appreciated

**Comment by NPohl-MSFT** [comment]
Hi @xiaoguid,

there are valid and expected exceptions during at disconnect. Disabling the exceptions in the debugger does not mean that they are somehow turned off, it just means that the debugger does not break immediately at the point where they are thrown. That is, before the program has even the chance to to catch and handle the exception. 

E.g. the following code will cause the debugger to break and show you a ExceptionThrown message, while the exception is actually handled just fine:
```
try
{
    throw winrt::hresult_error(E_FAIL, L"Something went wrong.");
}
catch (winrt::hresult_error& err)
{
    // handle error...
}
```

On the other hand, with the exception disabled in the Exception Settings window, if an exception is thrown and is not catched and handled, you will still get notified by the debugger.

Please also note that the disconnect is an asynchronous event. It can happen midway during the update or rendering. In this case, various Holographic API methods may return an error when called, which cppwinrt communicates by throwing a winrt::hresult_error. These should be catched and handled by the application, as demonstrated in the samples.

That said, if you're seeing crashes or unhandled exceptions that can't be handled by your code, we would be interested in more exception logs, ideally together with a small repro case, if possible.

**Comment by xiaoguid** [comment]
@NPohl-MSFT I appreciate the detailed explanation.

However I must have miscommunicated something, as I am very aware of first-chance exceptions in the debugger and the ability to disable them. Have been using that in projects for many years.

In the meantime since opening the issue I've updated to the latest cppwinrt and delayed the Disconnect even further which solved some of the issues I was having.

My remaining nitpick is that even delayed, imo, Disconnect should not throw exceptions.
But it sounds like having to disable the exception in the debugger is by design when working with the Holographic API, so I am closing the issue.
