### ISSUE TITLE
can't run normally in Hololens2

### ISSUE THREAD

**Issue by Lancename** [microsoft/MixedReality-HolographicRemoting-Samples#30]
Hello, thank you for providing such a convenient program.
Unfortunately, I now encounter a very strange problem.
At first, I can successfully compile and deploy the project to my Hololens2, and it can run normally.
But now I don't know why, after the deployment is successful, it can't run normally in Hololens2.
The phenomenon is as follows: when you open the application, you can see the initial holographic image. After you click the "Run" triangle button, you can see the rendering of the newly created holographic image space, but after a while, it can't run normally, and it returns to The original square image without any errors.
I tried to change the Win SDK to the recommended version (Windows SDK 10.0.18362.0) in the project. I also tried to change the computer (also the VS2019 community version), reset Hololens2, and even replaced a Hololens2, but it didn't work. .
My computer environment is VS2019 Community Edition
Win SDK is the latest version

**Comment by Lancename** [comment]
I builded the player sample.

**Comment by FlorianBagarMicrosoft** [comment]
@Lancename, thanks for reporting your issue.

To further investigate this issue it would be very useful for us if you could log the issue via [Feedback Hub](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).
When you add the feedback please ensure that you **recreate the problem** as described under point 8 in the link above. Also, please use **Windows Holographic** as category and use **All other issues** as sub-category. Beside this, it would be great if you could include **Custom Holographic Remoting Player closes unexpectedly** in your feedback item's name or description.

**Comment by Lancename** [comment]
@FlorianBagarMicrosoft thank you for reply so quickly. And I has loged th issue via Feedback hub.  But  because it is chinese， I can't make sure if it meet your requirements 
![image](https://user-images.githubusercontent.com/24515772/117973110-8d120c00-b35e-11eb-8b41-a88cf9a16f25.png)

**Comment by FlorianBagarMicrosoft** [comment]
Thanks! We will get back to you as soon as we know more.

**Comment by Lancename** [comment]
I  also try to deploy it by vs 2017+Windows SDK 10.0.18362.0，but it still didn't work.and showed some  error imformation as followed: 
![image](https://user-images.githubusercontent.com/24515772/118131725-77214b80-b431-11eb-98f7-b1e5081e91a2.png)
I am not sure that if it dues to the virsion of Microsoft.VCLibs.

**Comment by FlorianBagarMicrosoft** [comment]
@Lancename, did you manage to resolve the issue?

**Comment by Lancename** [comment]
@FlorianBagarMicrosoft   Yes，but I don't know why it can work,    I just tried it the same as before, and it worked. 
I noted that the prevision App in the store  also  couldn't work，event couldn't be download from the App store . so i just tried to reset  it  again.  And then  it worked....  
The other hololens2 that hadn't made any changes, also suddenly worked well. How amazing it is..
