### ISSUE TITLE
Could not see the sample results 

### ISSUE THREAD

**Issue by xiaolongrenlzj** [microsoft/MixedReality-HolographicRemoting-Samples#34]
Thank you for providing such a great project. The code for player works perfect for me. But for the remote app using openXR, I followed every step and installed everything it needed but when I deployed it to the PC, I did not find any space for inputting the IP address of HoloLens. I've attached a pic which shows what it looks like. The same for using the Mixed Reality runtime. I even tried to  use the 2.4.0 version of Holographic Remoting OpenXr but I got the same result. Could you please tell me how to fix it? Thanks a lot.
![8](https://user-images.githubusercontent.com/49846516/124813339-c3b96c80-df32-11eb-9f6c-7535f3f34c9d.png)

**Comment by FlorianBagarMicrosoft** [comment]
The IP address is passed to SampleRemoteOpenXr via command line parameters.

If you launch the sample from Visual Studio you can configure this via the Debugging in Property Pages:
![image](https://user-images.githubusercontent.com/52421566/124867717-e002eb00-dfbe-11eb-972f-0ad4b28c735d.png)

If you want to launch the sample without Visual Studio, do it via a Command Prompt like:
![image](https://user-images.githubusercontent.com/52421566/124868000-67e8f500-dfbf-11eb-8092-3e69da2e57b1.png)

**Comment by xiaolongrenlzj** [comment]
> The IP address is passed to SampleRemoteOpenXr via command line parameters.
> 
> If you launch the sample from Visual Studio you can configure this via the Debugging in Property Pages:
> ![image](https://user-images.githubusercontent.com/52421566/124867717-e002eb00-dfbe-11eb-972f-0ad4b28c735d.png)
> 
> If you want to launch the sample without Visual Studio, do it via a Command Prompt like:
> ![image](https://user-images.githubusercontent.com/52421566/124868000-67e8f500-dfbf-11eb-8092-3e69da2e57b1.png)

Thank you so much for your elaborate explanation. It works fine for v2.5.0 of Holographic Remoting OpenXr. But for v2.6.0, I tried to launch the sample with or without Visual Studio, it did not work and it looks like:
 
![9](https://user-images.githubusercontent.com/49846516/124969651-f6c43480-dff4-11eb-852e-cbc06a6ee637.png)

**Comment by maapp** [comment]
Hi @xiaolongrenlzj,

Can you please paste the whole command line you use when starting the RemoteOpenXr sample? We tried to repro it and I double checked our code. The IP address in the titlebar (and to which we connect to) is just taken from the command line options. We also didn't make any changes that I'm aware of between versions 2.5 and 2.6 in that area.

**Comment by maapp** [comment]
Hi @xiaolongrenlzj,

one other thing - did you update your player? A 2.6 remote application (like our OpenXR sample) can only connect to a player of version 2.6 and higher. You might need to force an update in the Windows Store if you use the normal player from there. If you have built a custom player you need to build a new one based on the current code on github.

**Comment by xiaolongrenlzj** [comment]
> Hi @xiaolongrenlzj,
> 
> one other thing - did you update your player? A 2.6 remote application (like our OpenXR sample) can only connect to a player of version 2.6 and higher. You might need to force an update in the Windows Store if you use the normal player from there. If you have built a custom player you need to build a new one based on the current code on github.

Thank you so much. I just updated my player and it worked.

**Comment by maapp** [comment]
Great that this was an easy fix, will close the ticket now. Thanks for the update!
