### ISSUE TITLE
Video Codec setting

### ISSUE THREAD

**Issue by xiaolongrenlzj** [microsoft/MixedReality-HolographicRemoting-Samples#35]
Hi,

I was trying to use different video codec methods to test our network by remoteXR. I noticed there was 4 parameters we could choose from.  Could you please tell me if I could transfer the video without compression? And what is the "XR_REMOTING_VIDEO_CODEC_MAX_ENUM_MSFT" method used for?

**Comment by FlorianBagarMicrosoft** [comment]
Transferring video without compression is not supported by Holographic Remoting, it's either HEVC or H264.

XR_REMOTING_VIDEO_CODEC_MAX_ENUM_MSFT marks the end of the XrRemotingVideoCodecMSFT enumeration. This is how OpenXR enumerations have to be specified to be standard conform. Have a look at the OpenXR core specification at https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html.

**Comment by maapp** [comment]
Closing the issue for now, if you need further help with the video codec configuration or so let us know.
