### ISSUE TITLE
Holographic Remoting Player always displays "Receiving..." without showing the unity editor

### ISSUE THREAD

**Issue by enrico-manzionna** [microsoft/MixedReality-HolographicRemoting-Samples#37]
good day to all,
I have been working with Holographic Remoting Player since  I want to see in my HoloLens 2 view what I'm actually seeing on the game view of my unity project, but I'm having some problems with this application :  when  I connect it to my unity project giving the IP address of the HoloLens the game view of my project changes wrt the way the HoloLens are oriented but on the HoloLens view I can only see the text "Receiving" and not the actual game view. Anyone knows how to solve this problem?

**Comment by maapp** [comment]
Hi @enrico-manzionna,

can you make sure that your HoloLens 2 is on the latest OS version and that you have the latest version of the remoting player installed (we just released version 2.6.1).

Besides that what version of Unity are you using and what type and version of the mixed reality binding in Unity?

Bye,
Marc

**Comment by maapp** [comment]
Closing this for now, let us know if you still have problems and need help.

**Comment by eternity123-null** [comment]
When I run samples ，it works. But when I tried on my own unity project,  it just show receiving. Why?

**Comment by FlorianBagarMicrosoft** [comment]
Hi @eternity123-null,
which Unity version are you using?

**Comment by eternity123-null** [comment]
> Hi @eternity123-null,
> which Unity version are you using?

the sample and my project are both on 2020.3.15 LTS

**Comment by FlorianBagarMicrosoft** [comment]
Have you done the XR Plug-in Management setup in your project?
https://docs.microsoft.com/windows/mixed-reality/develop/unity/unity-play-mode?tabs=openxr

**Comment by eternity123-null** [comment]
> Have you done the XR Plug-in Management setup in your project?
> https://docs.microsoft.com/windows/mixed-reality/develop/unity/unity-play-mode?tabs=openxr

oh , I forgot to select Windows Mixed Reality. Thank you very much !

**Comment by MarkvMars** [comment]
Too me ages to figure this out...when you press the play button in unity...and you see the receiving display in the hololens...press the pause button in unity and it will start working...not sure why...

your next question will be how to auomatically disable the profiler ... man I wish I knew the anwser to that...

**Comment by havadank** [comment]
I am running unity 2020.3 with the openXR plug in. I had the same problem, but I got it to work by selecting the "H264" instead of the "auto" in my holographic emulation window in unity.

**Comment by havadank** [comment]
> @havadank - good that you have thinks working. Any chance you can give us some details on your hardware? Are you running it on a laptop? CPU / GPU would be interesting. Thanks!

Yes I am running it on my laptop, a MateBook 13. It has an intel core i7 processor with 8GB RAM and a 64bits operative system. The GPU i am running is Intel UHD Graphics 620 since the NVIDA GeForce MX150 interfered with the connection in a previous project.

**Comment by chenritiana** [comment]
> > Hi @eternity123-null,
> > which Unity version are you using?
> 
> the sample and my project are both on 2020.3.15 LTS

Hi!Can you show me what the sample is? i also meet this problem for long time

**Comment by chenritiana** [comment]
> > Hi @eternity123-null,
> > which Unity version are you using?
> 
> the sample and my project are both on 2020.3.15 LTS

Hi! I meet the same problem but i don't know how to run the sample in unity,i see it's a cpp program. is it a deployed program?

**Comment by jonortega77** [comment]
> Too me ages to figure this out...when you press the play button in unity...and you see the receiving display in the hololens...press the pause button in unity and it will start working...not sure why...
> 
> your next question will be how to auomatically disable the profiler ... man I wish I knew the anwser to that...

This worked for me.
