### ISSUE TITLE
Ports used by client and server

### ISSUE THREAD

**Issue by Julian243** [microsoft/MixedReality-HolographicRemoting-Samples#43]
I want to use HolographicRemoting with an Android smartphone tethered to HoloLens2 in order to use our 5G network.
However the server initiates the conntection to the client which causes connection errors as the phone is acting as a second router, and won't forward unsolicited incoming traffic to devices behind it unless you forward ports on it.
I would therefore like to know which ports are used by client and server so I can forward them.

Thank you for your help!

**Comment by FlorianBagarMicrosoft** [comment]
Default port is 8265. See SampleRemoteApp::ConnectOrListen in https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/blob/main/remote/desktop/SampleRemoteApp.cpp.

**Comment by Julian243** [comment]
Sorry, another question: does Holographic Remoting use UDP or TCP. I'm using Unity as the server application in case it matters.

**Comment by fereeh** [comment]
The initial handshake is done via TCP. After the handshake succeeded all further communication happens via UDP.

**Comment by Julian243** [comment]
Thanks! Is it the same port 8265 for UDP and TCP?

**Comment by fereeh** [comment]
8265 is the TCP listening port and the UDP transport is using 8266 by default.
