### ISSUE TITLE
Timestamp synchronization

### ISSUE THREAD

**Issue by qian256** [microsoft/MixedReality-HolographicRemoting-Samples#47]
Hi remoting team, I wonder if the remote and player has a way to synchronize timestamps? For example, when both sides query their own system relative time, is there a way to calculate the exact difference between them? 
Does AppRemoting internally have it implemented, because the player needs to know the time that the remote side generate the images, so the player can re-project precisely?
Thanks!

**Comment by FlorianBagarMicrosoft** [comment]
Hi @qian256, sorry for the late response.
Yes clocks are synchronized between remote and player side but it's not exposed via our public API.
For re-projection time synchronization is not required but we need it to do the pose prediction.

**Comment by dfields-msft** [comment]
@qian256 can you provide some more details on the scenario you are trying to accomplish? Are you building a customized player app, or using the stock player app from the Microsoft Store?

**Comment by qian256** [comment]
Yes I am using a customized player. My remote player sends some events to remote side. I want to be able to relate the timestamp of the player side events with remote side events.

**Comment by dfields-msft** [comment]
Thanks - is your remote host (not player) using Unity, or some other framework?

**Comment by qian256** [comment]
Yes it is Unity

**Comment by maapp** [comment]
Hi @qian256,

what version of Unity are you using and are you using the OpenXR based MR plugin or the older Windows Holographic based one?
We're currently looking at this feature and having this information would help with planning.

Thanks,
Marc

**Comment by qian256** [comment]
@maapp I am using quite old version of Unity 2019.3.12f1, Legacy XR, AppRemoting 2.7.2. But I am open to newer versions too. The fix doesn't need to be on that old version

**Comment by simonrobl** [comment]
Hi @qian256, wanted to follow up with you to ask if this is still a requested use-case from your side? The API calls for this exist in [HAR](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/blob/6ef82dbacf9dbff4a5af677cce3850bb4bd2b43d/remote_openxr/specification.html#L4201C124-L4201C124), we'd be looking into making them available from the Open Xr Unity Plugin.

**Comment by simonrobl** [comment]
The requested functionality is available from Plugin Version 1.9 onwards with [AppRemoting.TryConvertToPlayerTime](https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.openxr.remoting.appremoting.tryconverttoplayertime) 
and [AppRemoting.TryConvertToRemoteTime](https://learn.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.openxr.remoting.appremoting.tryconverttoremotetime).
