### ISSUE TITLE
Support for XR_MSFT_perception_anchor_interop

### ISSUE THREAD

**Issue by Dakror** [microsoft/MixedReality-HolographicRemoting-Samples#52]
In order to facilitate local synchronization of multiple devices without the use of ASA, we would like to use the XR_MSFT_perception_anchor_interop extension to be able to use the SpatialAnchorTransferManager in WinRT to (de-)serialize the spatial anchors we get from OpenXR. It seems however that with holographic remoting, this extension is not available (atleast on my Hololens 2 device).

Is this correct and if so, would it be possible to implement a fix for that?
Thanks in advance.

**Comment by maapp** [comment]
Hi @Dakror ,

you're right - Holographic Remoting doesn't support the interop extension. And with our product architecture we can't support it either and we have no plans to introduce it.

I know you want to do it without ASA but ASA is the recommended way to use anchors on multiple devices.

Bye
Marc

**Comment by Dakror** [comment]
I understand, thank you regardless.
