### ISSUE TITLE
Inconsistencies when using XR_MSFT_hand_interaction input's with remoting

### ISSUE THREAD

**Issue by dnikolaidis2** [microsoft/MixedReality-HolographicRemoting-Samples#61]
**Describe the bug**
While reading /input/select/value and /input/squeeze/value inputs in a 1 - 1 test between native HoloLens 2 and using Holographic Remoting I get inconsistent values between the setups. While the values are read as a float in the remoting setup the returned values are always either 1 or 0. The value for /input/select/value also seems to be triggered less often then in the native setting. When running natively on a hololens I can get values between 0 and 1 for both inputs which does like the case when remoting.

**To Reproduce**
1. Enable XR_MSFT_hand_interaction.
2. Read /input/select/value and /input/squeeze/value as float.
3. Visualize output.
4. Repeat without remoting.

**Screenshots / videos**

**Remote side:**
 - OS version: Windows 10 Pro, 21H2, build 19044.1766
 - OpenXR Version 1.0.23
 - Microsoft.Holographic.Remoting.OpenXr, version 2.8.0, NuGet Package
 - NVIDIA GeForce GTX 1050 Ti Max-Q, driver 512.95 (30.0.15.1295)
 - Intel UHD Graphics, driver 27.20.100.8729

**Player side:**
 - HoloLens 2, Windows Holographic for Business, build 20348.1506
 - Store Holographic Remoting Player version 2.8.0.0

**Comment by NPohl-MSFT** [comment]
Thanks for the feedback! We will look into this issue and get back to you as soon as we know more.
