### ISSUE TITLE
Code for OpenXR will not compile Out of Box in VS 2022

### ISSUE THREAD

**Issue by laultman** [microsoft/MixedReality-HolographicRemoting-Samples#63]
After the Project is retargeted to VS 2022 in the options. (We do not have VS 2019 and are not allowed to install older components in new code dev/builds.)

**To Reproduce**
Obtain latest code from repository and unzip to a folder.
Open VS 2022 (latest install) and open the remoteOpenXR solution.
Right-click the Project name and choose Properties from the context menu.
Under Configuration Properties/General, from the right pane's General Properties/Platform Toolset dropdown select Visual Studio 2022 to retarget the solution.
Under Configuration Properties/Debugging in the right pane's property Command Line Arguments enter the IP address of your HoloLens 2 device.
Build the app.

This code produces an error:
#ifdef _MSC_VER
    template <typename X, typename Y>
    constexpr const X& cast(const Y& value) {
        static_assert(false, "Undefined cast from Y to type X");
    }
#endif

If you change the code for VS 2022 you do not get the error because you have effectively removed the cast template.
//#ifdef _MSC_VER
#if _MSC_VER <= 1929
    template <typename X, typename Y>
    constexpr const X& cast(const Y& value) {
        static_assert(false, "Undefined cast from Y to type X");
    }
#endif

In any case this code does not work while the remote WMR version does work.

**Screenshots / videos**
If applicable, add screenshots or videos to help explain your problem.

**Remote side (your Windows PC):**
 - OS version: [e.g. 21H2, build 22000.675]
 - Are you using an engine (Unity/Unreal), if yes - which one and which version: [e.g. Unity 2022.1.3f1]
 - Are you using OpenXR or Windows Holographic (or the respective plugins for your engine)
 - Are you using your own render engine? If so - what version of the remoting SDK are you using? [e.g. 2.8.0]
 - Graphics card(s) / graphics driver version: [e.g. nVidia RTX 3080 with driver version 511.23, also note if you have multiple GPUs in your system - a laptop with integrated and discrete graphics for example]

**Player side (e.g. your HoloLens 2)**
 - OS version
 - Are you using the remoting player from the store? If so which version is shown? [e.g. 2.8.0]
 - If you use a custom built player and have problems, did you try with the stock store player?

**Comment by maapp** [comment]
Hi @laultman,

a fix for this is coming in the next days :)

Thanks,
Marc

**Comment by maapp** [comment]
Hi,

with the latest which just went in the problems are fixed.
Let us know if you have any further problems!

Bye,
Marc
