### ISSUE TITLE
How to use ResearchModeApi to remotely connect hololens2 player through PC application

### ISSUE THREAD

**Issue by ccrop** [microsoft/MixedReality-HolographicRemoting-Samples#66]
Hi,
I need to get the depth camera data through remote rendering, but I encountered difficulties and asked for help.
How to use ResearchModeApi to remotely connect hololens2 player through PC application.

**Comment by Hanaae-MSFT** [comment]
Hey @ccrop,

ResearchModeApi can not be used to connect a remote app on PC to a HoloLens2 player. We would recommend for you though starting from the sample remote and sample player apps in this repository, to see how Holographic Remoting can be used to achieve your purpose, probably by using ResearchModeApi on the sample player side and then using a custom data channel to send depth camera data from the custom player on HoloLens 2 to the remote app.

Sample Remote: https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/tree/main/remote/desktop
Sample Player: https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/tree/main/player/sample
Custom data channel: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/holographic-remoting-custom-data-channels

Thanks,
Hanaa

**Comment by ccrop** [comment]
@Hanaae-MSFT Thank you very much for your advice.
I have seen some sample codes In MixedReality-HolographicRemoting-Samples,Moreover, we have written a custom player for use in hololens. but my PC app is developed with unity2020.3.35 MRTK. No interface for receiving custom data channels is found in unity mixed reality openxr. How will I implement it?

**Comment by Hanaae-MSFT** [comment]
Hey @ccrop 
Yeah, we have plans to add a Unity C# interface for custom remoting data channels in the mixed reality openxr plugin. However, so as to help us decide priorities because the team is heads down working on high-priority features at the moment, how urgent is this?

**Comment by Hanaae-MSFT** [comment]
Yeah, we have plans to add a Unity C# interface for custom remoting data channels in the mixed reality openxr plugin. However, so as to help us decide priorities because the team is heads down working on high-priority features at the moment, how urgent is this?

**Comment by Hanaae-MSFT** [comment]
Yeah, unfortunately that's true, but we have plans to add a Unity C# interface for custom remoting data channels in the mixed reality openxr plugin. However, so as to help us decide priorities because the team is heads down working on adding high-priority features at the moment, how urgent is this?

**Comment by ccrop** [comment]
Well, thank you very much. We applied camera to complete the object recognition at high frame rate to enhance the user's MR experience.We look forward to the rapid realization of this function.

**Comment by maapp** [comment]
Closing for now as the future work is tracked in bug 1386 on the Unity MR Plugin project.
