### ISSUE TITLE
2 holographic remote on same PC

### ISSUE THREAD

**Issue by almoga296** [microsoft/MixedReality-HolographicRemoting-Samples#68]
**Describe the bug**
I run into an issue with trying run 2 [holographic remote](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/tree/main/remote/desktop) instances on the same PC.
The first instance connects successfully while the other cant establish the connection and got disconnected immediately. The order doesn’t matters.

**My setup:**
I have 2 hololens2 headsets and 1 PC,
Each one of the hololens2 runs the latest sample from GitHub - [holographic remote player sample](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/tree/main/player) with the following configuration (first HoloLens2 with handshake port = 8265 & transport port = 8266, second HoloLens with handshake port = 8269 & transport port = 8270) – runs as listeners.
My PC runs 2 instances of the [holographic remote](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/tree/main/remote/desktop) with the related configuration (1 instance with remote port = 8265, 2 instance with remote port = 8269) – runs as clients.

**Remote side - Laptop:**
 - OS version:  WIN10 21H2, build 19044
 -  using Windows Holographic
 -  Nvidia RTX 3070 with driver version 30.0.15.1236

**Player side - HoloLens 2**
 - OS version: 20348.1513.arm64fre.fe_release_svc_sydney_rel_prod.220802-1135

Do the holographic remote client support multiple instances on same PC?
Do you have any idea what can cause that problem?

Almog

**Comment by FlorianBagarMicrosoft** [comment]
In general your scenario should work but the problem in your specific setup is the NVIDIA GPU. NVIDIA consumer cards only allow three parallel video encoding sessions. Our remoting sample uses two sessions per default, one for the color stream and one for the depth stream, say in your scenario the GPU needs to allow four parallel video encoding sessions.

You could try to disable depth via IRemoteContext::ConfigureDepthVideoStream, use DepthBufferStreamResolution::Disabled. This should get you going with your test.

**Comment by almoga296** [comment]
Dear Florian,
It seems to be the problem!
Thank you!

**Comment by ccrop** [comment]
@FlorianBagarMicrosoft  

> In general your scenario should work but the problem in your specific setup is the NVIDIA GPU. NVIDIA consumer cards only allow three parallel video encoding sessions. Our remoting sample uses two sessions per default, one for the color stream and one for the depth stream, say in your scenario the GPU needs to allow four parallel video encoding sessions.
> 
> You could try to disable depth via IRemoteContext::ConfigureDepthVideoStream, use DepthBufferStreamResolution::Disabled. This should get you going with your test.

I use unity OpenXR for remote rendering development,

How do I disable deep video streaming in unity .

**Comment by Hanaae-MSFT** [comment]
Hey ccrop,
You can disable depth in Unity OpenXR plugin by going to `Project Settings` and go to `OpenXR` under `Xr Plug-in Management`, there you can find an option `Depth Submission Mode`, and set it to `None`.
<img width="811" alt="image" src="https://user-images.githubusercontent.com/71517950/197985069-40d6a1d0-d027-4051-a0be-1b938dfa56f1.png">

**Comment by FlorianBagarMicrosoft** [comment]
Unfortunately it's currently not possible to disable the depth video stream when using Holographic Remoting with OpenXR in Unity. Holograms will be quite unstable without proper depth.
You can only disable the depth submission but this does not help here because the depth video stream will still be initialized.

**Comment by ccrop** [comment]
okay, thank you.
