### ISSUE TITLE
Support for Azure Spatial Anchors in windows based remote

### ISSUE THREAD

**Issue by almoga296** [microsoft/MixedReality-HolographicRemoting-Samples#69]
**Describe the bug**
I've opened Azure account and enabling the spatial anchors service to build spatially aware mixed reality application.
Clone Azure Spatial Anchors [github](https://github.com/Azure/azure-spatial-anchors-samples) sample. 
Can't run azure spatial anchors with holographic remoting (store edition), probably because lack of dll.

**Error:**
DllNotFoundException: AzureSpatialAnchors assembly:<unknown assembly> type:<unknown type> member:(null)
Microsoft.Azure.SpatialAnchors.AnchorLocateCriteria..ctor () (at Library/PackageCache/com.microsoft.azure.spatial-anchors-sdk.core@bd79930953e8/Runtime/Plugins/Standalone/AzureSpatialAnchorsBridge_Standalone.cs:1928)
Microsoft.Azure.SpatialAnchors.Unity.Examples.DemoScriptBase.Start () (at Assets/AzureSpatialAnchors.Examples/Scripts/DemoScriptBase.cs:112)
Microsoft.Azure.SpatialAnchors.Unity.Examples.AzureSpatialAnchorsSharedAnchorDemoScript.Start () (at Assets/AzureSpatialAnchors.Examples/Scripts/AzureSpatialAnchorsSharedAnchorDemoScript.cs:139)

It looks like Azure spatial anchors doesn't have the compatible .dll file for targeting WindowsStandalone build.

**Remote side - Laptop:**
 - OS version: WIN10 21H2, build 19044
 - Using Unity 2021.3.9f1 with MRTK holographic remote for play mode
 - Nvidia RTX 3070 with driver version 30.0.15.1236

**Player side - HoloLens 2**
 - OS version: 20348.1513.arm64fre.fe_release_svc_sydney_rel_prod.220802-1135
 - Store player 

Do you familiar with a way to achieve azure spatial anchor to work with holographic remote at all?
Do you familiar with other co-location sharing solution that can work with holographic remote &  hololens2?

Almog

**Comment by Hanaae-MSFT** [comment]
Hey @almoga296  
Looking at the stack trace you included, it doesn't seem to be a remoting-related issue but rather with the ASA SDK installation probably, since Unity can't find the dll. Does this happen only with holographic remoting on your side? We suggest that you follow up on it with the Azure Spatial Anchors team.

**Comment by cheles** [comment]
@almoga296  I've answered to your question raised here https://github.com/Azure/azure-spatial-anchors-samples/issues/371
