### ISSUE TITLE
UE4&Remote Player Connecting Issue

### ISSUE THREAD

**Issue by hanmoxu9** [microsoft/MixedReality-HolographicRemoting-Samples#70]
I was using UE4.27 before, it works perfect ,but a few days later,when I trys connecting the player,the Log shows :

LogTemp: Editor connecting to remote HoloLens2: 192.168.8.200
LogWmrHmd: WMRInterop: ConnectToRemoteHoloLens trying to connect to HoloLens2 192.168.8.200
LogWmrHmd: WMRInterop: RemotingDisconnectedEvent: Reason: 12 TransportConnectionFailed
LogHoloLensAR: Warning: HoloLens AR session disconnected from peer
LogWmrHmd: WMRInterop: DisconnectFromDevice: Disconnecting from wmr device.
LogWmrHmd: WMRInterop: DestroySpatialAnchorHelper

I don't understand what happend.I didn't do anything , just a few days!!!

Thanks for helping!

**Comment by cheles** [comment]
@hanmoxu9 I gave a try with basic sample following [these ](https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/XRDevelopment/AR/ARPlatforms/HoloLens/QuickStartStreaming/#:~:text=Go%20to%20Project%20Settings%20%3E%20Platform,of%20HoloLens%20to%20remote%20to.&text=In%20order%20for%20the%20HoloLens,same%20network%20as%20your%20PC.) steps w/ Unreal 4.27.2 and HL on same network. everything works as covered. might it be something that changed within your network?
can you access your Hololens in a browser by going to its IP?

**Comment by hanmoxu9** [comment]
> 

Thanks for replying,I have reinstalled my OS and fixed the issue, I guess the problem might be the OS software environment went wrong , anyway ,thanks again.
