### ISSUE TITLE
2 sample remote instances on same PC

### ISSUE THREAD

**Issue by almoga296** [microsoft/MixedReality-HolographicRemoting-Samples#71]
**Describe the bug**
I got 2 hololens2 headsets and 1 PC and run into an issue with try running 2 holographic remote ([Sample remote for desktop](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/tree/main/remote/desktop)) on same PC.

The link between the first pair of hololens2 <=> PC (remote) works well.
The 2nd one start to rendering frames and after about 1 second it throw the following exception:

 	[External Code]	
 	Microsoft.Holographic.AppRemoting.dll!00007ff91cb866b4()	Unknown
 	Microsoft.Holographic.AppRemoting.dll!00007ff91c68b0cf()	Unknown
 	Microsoft.Holographic.AppRemoting.dll!00007ff91c779f5c()	Unknown
 	Microsoft.Holographic.AppRemoting.dll!00007ff91c780b5a()	Unknown
	SampleRemote.exe!winrt::impl::consume_Windows_Graphics_Holographic_IHolographicCameraPose<winrt::Windows::Graphics::Holographic::IHolographicCameraPose>::HolographicCamera() Line 127	C++
 	SampleRemote.exe!SampleRemoteApp::Render::__l2::<lambda>(std::map<unsigned int,std::unique_ptr<DXHelper::CameraResourcesD3D11Holographic,std::default_delete<DXHelper::CameraResourcesD3D11Holographic>>,std::less<unsigned int>,std::allocator<std::pair<unsigned int const ,std::unique_ptr<DXHelper::CameraResourcesD3D11Holographic,std::default_delete<DXHelper::CameraResourcesD3D11Holographic>>>>> & cameraResourceMap) Line 534	C++
 	SampleRemote.exe!DXHelper::DeviceResourcesD3D11Holographic::UseHolographicCameraResources<void <lambda>(std::map<unsigned int,std::unique_ptr<DXHelper::CameraResourcesD3D11Holographic,std::default_delete<DXHelper::CameraResourcesD3D11Holographic>>,std::less<unsigned int>,std::allocator<std::pair<unsigned int const ,std::unique_ptr<DXHelper::CameraResourcesD3D11Holographic,std::default_delete<DXHelper::CameraResourcesD3D11Holographic>>>>> &)>(const SampleRemoteApp::Render::__l2::void <lambda>(std::map<unsigned int,std::unique_ptr<DXHelper::CameraResourcesD3D11Holographic,std::default_delete<DXHelper::CameraResourcesD3D11Holographic>>,std::less<unsigned int>,std::allocator<std::pair<unsigned int const ,std::unique_ptr<DXHelper::CameraResourcesD3D11Holographic,std::default_delete<DXHelper::CameraResourcesD3D11Holographic>>>>> &) & callback) Line 100	C++
 	SampleRemote.exe!SampleRemoteApp::Render(winrt::Windows::Graphics::Holographic::HolographicFrame holographicFrame) Line 521	C++
 	SampleRemote.exe!SampleRemoteApp::Tick() Line 99	C++
 	SampleRemote.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, wchar_t * lpCmdLine, int nShowCmd) Line 239	C++
 	[External Code]	

**To Reproduce**
1. Run 1st Hololens2 with store player (v2.8.1.0)
2. Run 1st [desktop executable](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/tree/main/remote/desktop) instance and connect the hololens2 IP.
3. Run 2nd Hololens2 with store player (v2.8.1.0)
4. Run 2nd [desktop executable](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/tree/main/remote/desktop) instance and connect the hololens2 IP.

**Screenshots / videos**
![image](https://user-images.githubusercontent.com/40126031/195035081-183e8000-c77e-46a5-93c3-f744c9302b36.png)

**Remote side (your Windows PC):**
 - OS version: WIN10 21H2, build 19044
 - NVIDIA RTX 3000

**Player side (e.g. your HoloLens 2)**
 - OS version: 20348.1513.arm64fre.fe_release_svc_sydney_rel_prod.220802-1135
 - I am using the remoting player from the store [v2.8.1.0]

**Comment by Hanaae-MSFT** [comment]
Hey,
The reason for what you are experiencing here is, as mentioned by my colleague in this previous [issue](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/issues/68) because NVIDIA consumer cards only allow three parallel video encoding sessions. Also, C++/WinRT exceptions are expected and you can disable them in visual studio.

**Comment by FlorianBagarMicrosoft** [comment]
NVIDIA RTX 3000 series is consumer grade hardware. All models from RTX 3050 up to RTX 3090 Ti are consumer grade GPUs. Non-consumer grade GPUs are Nvidia Quadro RTX for instance. Also, the GPU alone does not solve the issue, you also need Nvidia's GRID driver.

**Comment by almoga296** [comment]
Hey Hanaee & Florian,
You are both right, I meant to NVIDIA Quadro RTX 3000.
I will check the driver, as you mentioned @FlorianBagarMicrosoft 

Thanks,
Almog

**Comment by ccrop** [comment]
I am also troubled by this problem. I hope there is a solution.

**Comment by ccrop** [comment]
@FlorianBagarMicrosoft  Is there such a limit for amd consumer video cards,E.g RX6600XT?

**Comment by FlorianBagarMicrosoft** [comment]
@ccrop, there is not. We successfully tested with up to 20 encoder session.

**Comment by ccrop** [comment]
@FlorianBagarMicrosoft  Great, thank you very much!
