### ISSUE TITLE
Azure Spatial Anchors not working in UWP Unity build when using OpenXR Remoting

### ISSUE THREAD

**Issue by ikto-art** [microsoft/MixedReality-HolographicRemoting-Samples#73]
Hello,

I'm not sure if it was best to open this issue here or on the Azure Spatial Anchors repository, so I'll link it here in case it's more related to the remoting library than the ASA library:
Azure/azure-spatial-anchors-samples#381

Basically it seems that the current OpenXR Remoting runtime 2.8.1 is lacking OpenXR extensions for ASA to work properly, and I was under the impression that Azure Spatial Anchors were meant to work with Remoting apps in the latest 2.8.1 version.
If that's the case, will there be some support for this in the future?

The system we had before was to manually download anchors and map files from the HoloLens portal and transfer them to the other HoloLens devices and I was thinking of using the portal REST APIs to automatically do those transfers but I guess using ASA would be much more practical in the long term, or at least having access to the SpatialAnchorTransferManager with the remoting runtime.

By the way the reason for this request is that we want to use the Remoting library not only for previewing and development in Unity Play Mode but also definitively for rendering our content with powerful graphic cards.

**Comment by dfields-msft** [comment]
Hi @ikto-art, ASA indeed sounds like a good solution for your scenario, especially as an alternative to SpatialAnchorTransferManager. OpenXR Remoting 2.8.1 contains all the necessary platform support to enable ASA remoting - however there are some changes needed to the ASA SDK to fully enable this which are still pending. Can you please report this issue with the ASA team so we can engage in the proper context? Thanks!

https://github.com/Azure/azure-spatial-anchors-samples/issues

**Comment by dfields-msft** [comment]
Ah - looks like you already did, thanks!

https://github.com/Azure/azure-spatial-anchors-samples/issues/381
