### ISSUE TITLE
FPS locked to 30

### ISSUE THREAD

**Issue by almoga296** [microsoft/MixedReality-HolographicRemoting-Samples#83]
**Describe the bug**

Under heavy load task the application FPS locked to 30 fps - (profiler shows that), it released after the task finished.
While I check the fps via Hololens2 device portal I see that the holographic remote player running at 60fps.

Can I control it, make it not being locked (v-synced)?

**To Reproduce**
1. Launch remoting player on the HoloLens
2. Connect from any client
3. Try run any heavy CPU load task

**Screenshots / videos**
![image](https://user-images.githubusercontent.com/40126031/223709870-fd31cd81-ac9c-44d1-b4f8-fc1f4c999e0c.png)

**Remote side (your Windows PC):**
 - OS version: Win10 Pro 22H2
 - using Unity version: 2021.3.12f1
 - We are using OpenXR
 - Graphics card(s) / graphics driver version: I have 2 GPUs - NVIDIA RTX A5000 x2, driver version: 528.49
 - Player side (e.g. your HoloLens 2) your system - a laptop with integrated and discrete graphics for example]

**Player side (e.g. your HoloLens 2)**
 - OS version: 20348.1535.arm64fre.fe_release_svc_sydney_rel_prod.230106-1454
 - We use the store player version 2.8.1

**Comment by yl-msft** [comment]
@almoga296 , It's hard to tell from reports.  I have a few questions to clarify, hopefully can help us diagnose.

- Could you share the profiler file that shows the FPS lock?   How did you come to the conclusion that it's locked to 30fps? or just the app being running slow?
- Is your app has a desktop mirror view?
- Could you please help to take a ETL trace according to this instruction?   Use the command line workflow to take the trace of your remote app on PC.  https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/wiki/Troubleshooting-for-developers#capture-a-diagnostics-trace-from-the-command-line
- You can zip the files and share with me through discord, user name: yl-msft#5065

**Comment by yl-msft** [comment]
@almoga296, i've acceptted the friend request on discord.  Waiting for the trace file and see if I can discover anything.

It is interesting that you are using spout for video stream.   Are you also setting up the Spout Sender component to the main camera as instructed by the linked GitHub?  I wonder if this video capture component is the one who is locking the main camera's frame rate.  Can you double check, for example disable this component?  
![image](https://user-images.githubusercontent.com/33265158/225732219-58f55035-97a0-4833-ba3b-63c70e362994.png)

**Comment by yl-msft** [comment]
@almoga296 , we've not heard from you for a while.  Have you investigated if this "SpoutSender" is causing the FPS lock when it's doing video capture?  Or do you have further investigation on this issue?
