### ISSUE TITLE
Holographic remote app interleave all audio streams from PC

### ISSUE THREAD

**Issue by almoga296** [microsoft/MixedReality-HolographicRemoting-Samples#92]
**Describe the bug**
While using holographic remote application, the audio stream returned to the hololens2 device is consist of all running applications audio outputs.

Is there a way to filter only the remote application audio stream, instead play all PC audio streams?

I saw here: https://learn.microsoft.com/en-us/windows/mixed-reality/develop/native/holographic-remoting-version-history#version-291-february-17-2023- 
that in version 2.9.0 you have added: "support for per app audio capturing".
I didn't find any reference not in docs nor in code that explain that feature.
I'm not sure if it helpful or not, Do you know what is that?

**To Reproduce**
1. Launch remoting player on the HoloLens2
2. Connect from any remote application you built, also the remote sample is good.
3. Try play any audio source such as youtube on PC.
4. You will hear youtube audio on hololens2 internal speakers.

**Remote side (Windows PC)**
OS version: Win10 Pro 22H2
Unity version: 2021.3.12f1
We are using OpenXR.
Graphics card(s) / graphics driver version: 2 GPUs - NVIDIA RTX A5000 x2, driver version: 528.49
Player side (e.g. your HoloLens 2) your system - a laptop with integrated and discrete graphics for example]

**Player side (e.g. your HoloLens 2)**
OS version: 20348.1535.arm64fre.fe_release_svc_sydney_rel_prod.230106-1454
We use the store player version 2.9.2

**Comment by almoga296** [comment]
Thank you @Hanaae-MSFT !
I will wait for the update.

**Comment by Hanaae-MSFT** [comment]
Hey @almoga296 

The feature is finally exposed via the openxr plugin API. You can finally give it a spin and let us know.

**Comment by simonrobl** [comment]
As this ticket hasn't been active for some time now I'm closing it. @almoga296 feel free to reopen it if you're still encountering issues :)
