### ISSUE TITLE
QR Code connection with Holographic Remoting Player v2.9.2 

### ISSUE THREAD

**Issue by simonrobl** [microsoft/MixedReality-HolographicRemoting-Samples#97]
it's so upset that i encounter like the same question,when i using the 'connect' command in order to scan the QR code,but nothing changed on my hololens2,it's seem the holographic remoting player can't recognize the voice command,but the command 'enable diagnostics' can be recognized in my holographic remoting player v2.9.2.0,anyone can help me of that?

_Originally posted by @luoxiali in https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/issues/16#issuecomment-1725248474_

**Comment by simonrobl** [comment]
Please provide me with the following information, as referenced in our [issue template](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/blob/main/.github/ISSUE_TEMPLATE/general-issue.md):


**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**
Steps to reproduce the behavior:
1. Launch remoting player on the HoloLens
2. Connect from ....
3. Try '....'
4. See problem..

**Screenshots / videos**
If applicable, add screenshots or videos to help explain your problem.

**Remote side (your Windows PC):**
 - OS version: [e.g. 22H2, build 22000.675]
 - Are you using an engine (Unity/Unreal), if yes - which one and which version: [e.g. Unity 2023.1.3f1]
 - Are you using OpenXR or Windows Holographic (or the respective plugins for your engine)
 - Are you using your own render engine? If so - what version of the remoting SDK are you using? [e.g. 2.8.0]
 - Graphics card(s) / graphics driver version: [e.g. nVidia RTX 3080 with driver version 511.23, also note if you have multiple GPUs in your system - a laptop with integrated and discrete graphics for example]

**Player side (e.g. your HoloLens 2)**
 - OS version
 - Are you using the remoting player from the store? If so which version is shown? [e.g. 2.9.0]
 - If you use a custom built player and have problems, did you try with the stock store player?

**Comment by simonrobl** [comment]
Closed with no reply. If the issue persists feel free to reopen 👍

**Comment by luoxiali** [comment]
sorry too late to reply you comment,i have resolved it as it's my self problem that i generate a error link QR code,it's works when i changed the pure text to generate the QR code.thanks your previous reply!

**Comment by luoxiali** [comment]
sorry too late to reply you comment,i have resolved it as it's my self problem that i generate a error link QR code,it's works when i changed the pure text to generate the QR code.thanks your previous reply!

> Please provide me with the following information, as referenced in our [issue template](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples/blob/main/.github/ISSUE_TEMPLATE/general-issue.md):
> 
> **Describe the issue** A clear and concise description of what the issue is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Launch remoting player on the HoloLens
> 2. Connect from ....
> 3. Try '....'
> 4. See problem..
> 
> **Screenshots / videos** If applicable, add screenshots or videos to help explain your problem.
> 
> **Remote side (your Windows PC):**
> 
> * OS version: [e.g. 22H2, build 22000.675]
> * Are you using an engine (Unity/Unreal), if yes - which one and which version: [e.g. Unity 2023.1.3f1]
> * Are you using OpenXR or Windows Holographic (or the respective plugins for your engine)
> * Are you using your own render engine? If so - what version of the remoting SDK are you using? [e.g. 2.8.0]
> * Graphics card(s) / graphics driver version: [e.g. nVidia RTX 3080 with driver version 511.23, also note if you have multiple GPUs in your system - a laptop with integrated and discrete graphics for example]
> 
> **Player side (e.g. your HoloLens 2)**
> 
> * OS version
> * Are you using the remoting player from the store? If so which version is shown? [e.g. 2.9.0]
> * If you use a custom built player and have problems, did you try with the stock store player?

**Comment by simonrobl** [comment]
Thanks for letting me know, I'm glad to hear you got it resolved!
